name: CI MySQL + Python
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install mysql-connector-python pytest

      - run: sleep 25

      - name: Criar banco e tabela
        run: mysql -h 127.0.0.1 -u root -proot < tabela.sql

      - name: Popular banco
        run: mysql -h 127.0.0.1 -u root -proot < dados.sql

      - name: Mostrar tabela no log
        run: mysql -h 127.0.0.1 -u root -proot -e "USE db_alimentos; SELECT * FROM frutas;"

      - name: Rodar testes
        run: pytest -s