name: Entrega Final - CI/CD MySQL & Python

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: meubanco
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 🔽 PASSO QUE FALTAVA (BAIXAR O REPO)
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install mysql-connector-python

      # 🔽 esperar o MySQL iniciar
      - name: Esperar MySQL iniciar
        run: sleep 20

      # 🔽 IMPORTAR O BANCO (AGORA O ARQUIVO EXISTE)
      - name: Criar tabelas no MySQL
        run: mysql -h 127.0.0.1 -u root -proot meubanco < tabela.sql

      # 🔽 rodar o script python
      - name: Rodar script Python
        run: python app.py