name: CI MySQL Python

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install mysql-connector-python pytest

      - name: Aguardar MySQL iniciar
        run: sleep 25

      - name: Criar banco + tabela + dados
        run: mysql -h 127.0.0.1 -u root -proot < db_alimentos.sql

      - name: Rodar testes
        run: pytest -s